### ISSUE TITLE
Create a wireframe for Sign Up/Login page

### ISSUE THREAD

**Issue by dluangrath** [Matthew-Allen-1/internship-project-management#21]
Here are some inspos from project management/ task management login pages

<img width="956" alt="clickup_login" src="https://user-images.githubusercontent.com/89706454/207206294-221ebc4c-73b2-4d11-be5d-5159354802a8.png">
<img width="944" alt="clickup_signup" src="https://user-images.githubusercontent.com/89706454/207206309-d1602352-f86f-4abe-8b4f-a7a962e9ac64.png">

**Comment by dluangrath** [comment]
<img width="944" alt="clockify_login" src="https://user-images.githubusercontent.com/89706454/207206461-ddab093a-fb6a-4b75-8d1a-a7d450a7fac3.png">
<img width="946" alt="clockify_signup" src="https://user-images.githubusercontent.com/89706454/207206469-e74ae680-9d53-4e00-9f8c-164182dd9718.png">

**Comment by dluangrath** [comment]
<img width="949" alt="trello_login" src="https://user-images.githubusercontent.com/89706454/207206578-faad0b56-3d4f-4764-84c5-2ed5a22f31d4.png">
<img width="943" alt="monday_login" src="https://user-images.githubusercontent.com/89706454/207206621-ae5ee111-23e8-4974-95c3-2afc9ccf6ef3.png">
<img width="950" alt="monday_signup" src="https://user-images.githubusercontent.com/89706454/207206626-c3e0b12f-f380-4a2e-8511-821f0fc19800.png">

**Comment by JohnnyParra** [comment]
Pushed an Outline to the project under pages folder
